language: php

sudo: false

cache:
    directories:
        - vendor
        - $HOME/.composer/cache/files

env:
    - DEPS=no
    - INSTALL_PACKAGE_VERSIONS=no

before_install:
    - phpenv config-rm xdebug.ini

before_script:
    - if [ "$DEPS" == "low" ]; then composer --prefer-lowest --prefer-stable update; fi;
    - if [ "$DEPS" == "no" ]; then composer install; fi;
    - if [ "$INSTALL_PACKAGE_VERSIONS" == "yes" ]; then composer require --dev ocramius/package-versions jean85/pretty-package-versions; fi;

script: |
    ./vendor/bin/simple-phpunit

matrix:
    include:
        - php: 5.3
          dist: precise
        - php: 5.4
        - php: 5.5
        - php: 5.6
          env: DEPS=low
        - php: 7.0
          env: INSTALL_PACKAGE_VERSIONS=yes
        - php: 7.1
          env: INSTALL_PACKAGE_VERSIONS=yes
        - php: 7.2
          env: INSTALL_PACKAGE_VERSIONS=yes
    fast_finish: true
