language: php

before_script:
    - composer install --prefer-source
    - if [[ "$TRAVIS_PHP_VERSION" == "hhvm" ]]; then echo hhvm.enable_zend_compat=true | sudo tee -a /etc/hhvm/php.ini; fi

script: phpunit

php:
  - 5.3
  - 5.4
  - 5.5
  - hhvm
