language: php

sudo: false

cache:
    directories:
        - vendor
        - $HOME/.composer/cache

env:
    globals:
        - deps=no

before_script:
    - if [ "$deps" = "low" ]; then composer --prefer-lowest --prefer-stable update; fi;
    - if [ "$deps" = "no" ]; then composer install; fi;
    - if [ "$TRAVIS_PHP_VERSION" = "hhvm" ]; then grep "enable_zend_compat" /etc/hhvm/php.ini || cat .travis.hhvm.ini >> /etc/hhvm/php.ini ; fi

script: phpunit

matrix:
    include:
        - php: hhvm
        - php: 5.3
        - php: 5.4
        - php: 5.5
        - php: 5.6
          env: deps=low
        - php: 7.0
    fast_finish: true
